tools:
  jdk:
    - 8
  maven:
    - 3.5.0

triggers:
  - cron:
      spec: 0 17 * * *
      timezone: Europe/London
#envs:
#  global:
#    variables:
#      CHROME_BIN: /bin/chromium-browser

flows:
  default:
    try:
      - mvn clean verify -Dsurefire.suiteXmlFiles=testngParallel.xml
#      - call: slack-success
    catch:
#      - call: slack-failure
      - exit 1

#  slack-success:
#    - exposeVars(results.json)
#    - slack.postMessage:
#        message: "Regression on - ${results.appVersion}. Passed:${results.passCounter}, Failed:${results.failCounter}"
#        channelId: 'sng_mobile_automation'
#        iconEmoji: ':white_check_mark:'
#        username: 'Scan and Go - Perfecto Framework'
#        attachments:
#          - fallback: "https://ci.electrode.walmart.com/job/ASDA_SNG_Mobile/job/Scan_n_go_Perfecto/"#point to your report portal
#            actions:
#              - type: "button"
#                text: "Cucumber Report"
#                url: "${REPORT_URL}"
#              - type: "button"
#                text: "Report Portal Navigation"
#                url: "http://10.143.66.111:8080/ui/#customer_tower_automation/launches/312"
#
#  slack-failure:
#    - exposeVars(results.json)
#    - slack.postMessage:
#        message: "Regression on - ${results.appVersion}. Passed:${results.passCounter}, Failed:${results.failCounter}"
#        channelId: 'sng_mobile_automation'
#        iconEmoji: ':x:'
#        username: 'Scan and Go - Perfecto Framework'
#        attachments:
#          - fallback: "https://ci.electrode.walmart.com/job/ASDA_SNG_Mobile/job/Scan_n_go_Perfecto/"#point to your looper project
#            actions:
#              - type: "button"
#                text: "Cucumber Report"
#                url: "${REPORT_URL}"
#              - type: "button"
#                text: "Report Portal Navigation"
#                url: "http://10.143.66.111:8080/ui/#customer_tower_automation/launches/312"